import React, { useState, useEffect } from 'react';
import type { User, UserFormData, UserStatus, UserRole } from '../../types';
import { apiService } from '../../utils/api';
import { useTranslation } from 'react-i18next';
import './UserManagement.css';

const UserManagement: React.FC = () => {
  const { t, i18n } = useTranslation();
  const [users, setUsers] = useState<User[]>([]);
  const [showAddUser, setShowAddUser] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(true);
  const [actionLoading, setActionLoading] = useState<number | null>(null);
  const [error, setError] = useState<string>('');
  const [success, setSuccess] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filterRole, setFilterRole] = useState<string>('all');
  const [filterDepartment, setFilterDepartment] = useState<string>('all');
  const [managers, setManagers] = useState<User[]>([]);
  const [departments, setDepartments] = useState<string[]>([]);
  const [availableManagers, setAvailableManagers] = useState<User[]>([]);
  const [isNewDepartment, setIsNewDepartment] = useState<boolean>(false);
  const [newDepartmentName, setNewDepartmentName] = useState<string>('');
  const [emailError, setEmailError] = useState<string>('');

  const [autoGeneratedEmail, setAutoGeneratedEmail] = useState<string>('');
  
  const [newUser, setNewUser] = useState<UserFormData>({
    name: '',
    email: '',
    role: 'employee',
    department: '',
    position: '',
    phone: '',
    password: 'default123',
    managerId: ''
  });

  // Load users and initial data
  useEffect(() => {
    loadUsers();
    loadInitialData();
  }, []);

  const loadUsers = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await apiService.getUsers();
      
      if (response.success) {
        setUsers(response.data || []);
        extractDepartments(response.data || []);
      } else {
        setError(response.message || t('user_management.errors.load_failed'));
      }
    } catch (error: any) {
      console.error('Error loading users:', error);
      setError(error.message || t('user_management.errors.load_failed'));
    } finally {
      setLoading(false);
    }
  };

  const loadInitialData = async () => {
    try {
      const response = await apiService.getUsers();
      if (response.success) {
        const allUsers = response.data || [];
        const managerUsers = allUsers.filter(user => 
          ['manager', 'hr-admin', 'super-admin'].includes(user.role)
        );
        setManagers(managerUsers);
        extractDepartments(allUsers);
      }
    } catch (error) {
      console.error('Error loading initial data:', error);
    }
  };

  const extractDepartments = (userList: User[]) => {
    const uniqueDepartments = [...new Set(
      userList
        .map(user => user.department)
        .filter(Boolean)
        .sort()
    )] as string[];
    setDepartments(uniqueDepartments);
  };

  // Generate email from name
  const generateEmailFromName = (name: string): string => {
    if (!name.trim()) return '';
    
    const nameParts = name.trim().split(' ').filter(part => part.length > 0);
    
    if (nameParts.length === 0) return '';
    
    // First name (all lowercase)
    const firstName = nameParts[0].toLowerCase();
    
    // Last name initial (capitalized)
    let lastNameInitial = '';
    if (nameParts.length > 1) {
      lastNameInitial = nameParts[nameParts.length - 1].charAt(0).toUpperCase();
    }
    
    // Generate base email
    let baseEmail = `${firstName}${lastNameInitial}`;
    
    // Remove special characters and non-English letters
    baseEmail = baseEmail.replace(/[^a-zA-Z]/g, '');
    
    // Add domain
    return `${baseEmail}@obu.edu.et`;
  };

  // Generate unique email by checking existing users
  const generateUniqueEmail = (baseEmail: string, existingUsers: User[]): string => {
    let finalEmail = baseEmail;
    let counter = 1;
    
    // Check if email already exists
    const emailExists = (email: string) => {
      return existingUsers.some(user => 
        user.email.toLowerCase() === email.toLowerCase() && user.status === 'active'
      );
    };
    
    // If base email exists, try with numbers
    while (emailExists(finalEmail) && counter < 100) {
      const [localPart] = baseEmail.split('@');
      finalEmail = `${localPart}${counter}@obu.edu.et`;
      counter++;
    }
    
    return finalEmail;
  };

  // Handle name change and auto-generate email
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    
    setNewUser(prev => ({
      ...prev,
      name
    }));

    // Auto-generate email when name is entered
    if (name.trim().length > 0) {
      const generatedEmail = generateEmailFromName(name);
      setAutoGeneratedEmail(generatedEmail);
      
      // Only auto-fill email if it's empty or matches previous auto-generated pattern
      const currentEmail = newUser.email;
      const isAutoGenerated = currentEmail.includes('@obu.edu.et') || currentEmail === '';
      
      if (isAutoGenerated) {
        setNewUser(prev => ({
          ...prev,
          email: generatedEmail
        }));
      }
    } else {
      setAutoGeneratedEmail('');
    }

    // Clear messages when user starts typing
    if (success || error) {
      setSuccess('');
      setError('');
    }
  };

  // Handle manual email change
  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const email = e.target.value;
    
    setNewUser(prev => ({
      ...prev,
      email
    }));

    setEmailError('');
    
    // Validate email format
    if (email && !email.includes('@obu.edu.et')) {
      setEmailError(t('user_management.errors.email_domain'));
    } else if (email && email.includes('@obu.edu.et')) {
      setEmailError('');
    }
  };

  // Regenerate email button handler
  const handleRegenerateEmail = () => {
    if (newUser.name.trim()) {
      const baseEmail = generateEmailFromName(newUser.name);
      const uniqueEmail = generateUniqueEmail(baseEmail, users);
      setNewUser(prev => ({
        ...prev,
        email: uniqueEmail
      }));
      setAutoGeneratedEmail(uniqueEmail);
      setEmailError('');
    }
  };

  // Load managers when department changes
  useEffect(() => {
    if (newUser.department && newUser.role === 'employee') {
      loadManagersForDepartment(newUser.department);
    } else {
      setAvailableManagers([]);
    }
  }, [newUser.department, newUser.role]);

  const loadManagersForDepartment = async (department: string) => {
    try {
      const departmentManagers = managers.filter(manager => 
        manager.department === department
      );
      setAvailableManagers(departmentManagers);
    } catch (error) {
      console.error('Error loading managers:', error);
      setAvailableManagers([]);
    }
  };

  const handleAddUser = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    
    try {
      setError('');
      setSuccess('');
      setEmailError('');

      // Validate all required fields
      if (!newUser.name || !newUser.email || !newUser.department) {
        setError(t('user_management.errors.required_fields'));
        return;
      }

      // Validate email format
      if (!newUser.email.includes('@obu.edu.et')) {
        setEmailError(t('user_management.errors.email_domain'));
        return;
      }

      // Validate email doesn't exist in current active users
      const existingUser = users.find(user => 
        user.email.toLowerCase() === newUser.email.toLowerCase() && user.status === 'active'
      );

      if (existingUser) {
        setEmailError(t('user_management.errors.email_used', { name: existingUser.name }));
        return;
      }

      // Use new department name if "Add New" was selected
      const finalDepartment = isNewDepartment ? newDepartmentName : newUser.department;

      // Prepare user data
      const userData: any = {
        name: newUser.name.trim(),
        email: newUser.email.toLowerCase().trim(),
        role: newUser.role,
        department: finalDepartment.trim(),
        password: newUser.password
      };

      // Only add optional fields if they have values
      if (newUser.position?.trim()) userData.position = newUser.position.trim();
      if (newUser.phone?.trim()) userData.phone = newUser.phone.trim();

      // Only include managerId for employees and if manager is selected
      if (newUser.role === 'employee' && newUser.managerId) {
        userData.managerId = parseInt(newUser.managerId);
      }

      console.log('Creating user with data:', userData);

      const response = await apiService.createUser(userData);
      
      if (response.success) {
        setSuccess(t('user_management.messages.created', { name: newUser.name, email: newUser.email }));
        await loadUsers();
        resetForm();
        setShowAddUser(false);
      } else {
        if (response.message?.includes('email already exists')) {
          // Auto-generate a new unique email and suggest it
          const newEmail = generateUniqueEmail(autoGeneratedEmail, users);
          setEmailError(t('user_management.errors.email_exists_suggested', { email: newEmail }));
          setNewUser(prev => ({ ...prev, email: newEmail }));
        } else {
          setError(response.message || t('user_management.errors.create_failed'));
        }
      }
    } catch (error: any) {
      console.error('Error creating user:', error);
      
      if (error.message.includes('email already exists')) {
        const newEmail = generateUniqueEmail(autoGeneratedEmail, users);
        setEmailError(t('user_management.errors.email_exists_suggested', { email: newEmail }));
        setNewUser(prev => ({ ...prev, email: newEmail }));
      } else {
        setError(error.message || t('user_management.errors.create_failed'));
      }
    }
  };

  const handleDeleteUser = async (userId: number): Promise<void> => {
    if (!window.confirm(t('user_management.confirm_delete'))) {
      return;
    }

    try {
      setActionLoading(userId);
      setError('');
      setSuccess('');

      const response = await apiService.deleteUser(userId);
      
      if (response.success) {
        setSuccess(t('user_management.messages.deleted'));
        await loadUsers();
      } else {
        setError(response.message || t('user_management.errors.delete_failed'));
      }
    } catch (error: any) {
      console.error('Error deleting user:', error);
      setError(error.message || t('user_management.errors.delete_failed'));
    } finally {
      setActionLoading(null);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>): void => {
    const { name, value } = e.target;
    setNewUser(prev => ({
      ...prev,
      [name]: value
    }));

    // Clear success/error when user starts typing
    if (success || error) {
      setSuccess('');
      setError('');
    }
  };

   const handleDepartmentChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedValue = e.target.value;
    
    if (selectedValue === 'new') {
      setIsNewDepartment(true);
      setNewUser(prev => ({
        ...prev,
        department: ''
      }));
      setNewDepartmentName('');
    } else {
      setIsNewDepartment(false);
      setNewUser(prev => ({
        ...prev,
        department: selectedValue,
        managerId: ''
      }));
    }
  };

  const handleNewDepartmentChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setNewDepartmentName(value);
    setNewUser(prev => ({
      ...prev,
      department: value
    }));
  };

  const handleRoleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const role = e.target.value as UserRole;
    setNewUser(prev => ({
      ...prev,
      role,
      managerId: role !== 'employee' ? '' : prev.managerId
    }));
  };
  
  const handleStatusToggle = async (userId: number, currentStatus: UserStatus | undefined): Promise<void> => {
    const newStatus: UserStatus = currentStatus === 'active' ? 'inactive' : 'active';
    
    try {
      setActionLoading(userId);
      setError('');
      setSuccess('');

      // Update local state immediately for better UX
      setUsers(prevUsers => 
        prevUsers.map(user => 
          user.id === userId 
            ? { ...user, status: newStatus }
            : user
        )
      );

      const response = await apiService.updateUser(userId, { status: newStatus });

      if (!response.success) {
        throw new Error(response.message || 'Failed to update user status');
      }

      setSuccess(newStatus === 'active' ? t('user_management.messages.activated') : t('user_management.messages.deactivated'));
      
    } catch (error: any) {
      console.error('Error updating user status:', error);
      setError(error.message || t('user_management.errors.update_status'));
      
      // Revert local state on error
      setUsers(prevUsers => 
        prevUsers.map(user => 
          user.id === userId 
            ? { ...user, status: currentStatus }
            : user
        )
      );
    } finally {
      setActionLoading(null);
    }
  };

 const resetForm = (): void => {
    setNewUser({
      name: '',
      email: '',
      role: 'employee',
      department: '',
      position: '',
      phone: '',
      password: 'default123',
      managerId: ''
    });
    setIsNewDepartment(false);
    setNewDepartmentName('');
    setAvailableManagers([]);
    setEmailError('');
    setError('');
    setSuccess('');
    setAutoGeneratedEmail('');
  };

 const generatePassword = (): void => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
    let password = '';
    for (let i = 0; i < 12; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setNewUser(prev => ({ ...prev, password }));
  };


  // Filter users based on search and filters
  const filteredUsers = users.filter(user => {
    const matchesSearch = user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         user.email.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesRole = filterRole === 'all' || user.role === filterRole;
    const matchesDepartment = filterDepartment === 'all' || user.department === filterDepartment;
    
    return matchesSearch && matchesRole && matchesDepartment;
  });

  const formatDate = (dateString: string) => {
    const localeMap: Record<string, string> = { en: 'en-US', am: 'am-ET', om: 'om-ET' };
    const locale = localeMap[i18n.language] || 'en-US';
    return new Date(dateString).toLocaleDateString(locale, {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const getRoleDisplayName = (role: string) => {
    const roleKey = `roles.${role}`;
    return t(roleKey, { defaultValue: role });
  };

  const clearMessages = (): void => {
    setError('');
    setSuccess('');
  };

  if (loading) {
    return (
      <div className="user-management">
        <div className="page-header">
          <h2>{t('user_management.title')}</h2>
        </div>
        <div className="loading-state">
          <div className="loading-spinner"></div>
          <p>{t('user_management.loading')}</p>
        </div>
      </div>
    );
  }

  return (
    <div className="user-management">
      <div className="page-header">
        <div className="header-content">
          <div className="header-title">
            <h2>{t('user_management.title')}</h2>
            <span className="user-count-badge">{t('user_management.user_count', { count: users.length })}</span>
          </div>
          <button 
            className="add-user-btn primary"
            onClick={() => setShowAddUser(true)}
          >
            <span className="btn-icon">+</span>
            {t('user_management.add_user')}
          </button>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="filters-section">
        <div className="search-box">
          <input
            type="text"
            placeholder={t('user_management.search_placeholder')}
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
          <span className="search-icon">🔍</span>
        </div>
        
        <div className="filter-controls">
          <select 
            value={filterRole} 
            onChange={(e) => setFilterRole(e.target.value)}
            className="filter-select"
          >
            <option value="all">{t('user_management.filters.all_roles')}</option>
            <option value="employee">{t('roles.employee')}</option>
            <option value="manager">{t('roles.manager')}</option>
            <option value="hr-admin">{t('roles.hr-admin')}</option>
            <option value="super-admin">{t('roles.super-admin')}</option>
          </select>

          <select 
            value={filterDepartment} 
            onChange={(e) => setFilterDepartment(e.target.value)}
            className="filter-select"
          >
            <option value="all">{t('user_management.filters.all_departments')}</option>
            {departments.map(dept => (
              <option key={dept} value={dept}>{dept}</option>
            ))}
          </select>

          <button 
            className="refresh-btn"
            onClick={loadUsers}
            title={t('user_management.refresh')}
          >
            🔄 {t('user_management.refresh')}
          </button>
        </div>
      </div>

      {/* Messages */}
      {error && (
        <div className="message-banner error">
          <div className="message-content">
            <span className="message-icon">❌</span>
            {error}
          </div>
          <button onClick={clearMessages} className="message-close" aria-label={t('common.close')}>×</button>
        </div>
      )}

      {success && (
        <div className="message-banner success">
          <div className="message-content">
            <span className="message-icon">✅</span>
            {success}
          </div>
          <button onClick={clearMessages} className="message-close" aria-label={t('common.close')}>×</button>
        </div>
      )}

      {/* Add User Modal */}
       {showAddUser && (
        <div className="modal-overlay">
          <div className="modal-content" role="dialog" aria-modal="true" aria-label={t('user_management.modal.add_title')}>
            <div className="modal-header">
              <h3>{t('user_management.modal.add_title')}</h3>
              <button 
                className="close-btn"
                onClick={() => {
                  setShowAddUser(false);
                  resetForm();
                }}
                aria-label={t('common.close')}
              >
                ×
              </button>
            </div>
            
            <form onSubmit={handleAddUser} className="user-form">
              <div className="form-section">
                <h4>{t('user_management.modal.basic_info')}</h4>
                <div className="form-row">
                  <div className="form-group">
                    <label>{t('user_management.fields.full_name')} *</label>
                    <input
                      type="text"
                      name="name"
                      value={newUser.name}
                      onChange={handleNameChange}
                      required
                      placeholder={t('user_management.placeholders.full_name')}
                    />
                  <small className="help-text">
                      {t('user_management.help.full_name')}
                    </small>
                  </div>
                  <div className="form-group">
                    <label>{t('user_management.fields.email')} *</label>
                    <div className="email-input-group">
                      <input
                        type="email"
                        name="email"
                        value={newUser.email}
                        onChange={handleEmailChange}
                        required
                        placeholder={t('user_management.placeholders.email')}
                        className={emailError ? 'error' : (newUser.email ? 'success' : '')}
                      />
                      <button 
                        type="button" 
                        className="generate-email-btn"
                        onClick={handleRegenerateEmail}
                        disabled={!newUser.name.trim()}
                        title={t('user_management.actions.generate_email')}
                      >
                        🔄
                      </button>
                    </div>
                    {autoGeneratedEmail && (
                      <small className="help-text">
                        {t('user_management.help.auto_generated', { email: autoGeneratedEmail })}
                      </small>
                    )}
                    {emailError && (
                      <small className="error-text">{emailError}</small>
                    )}
                    {!emailError && newUser.email && newUser.email.includes('@obu.edu.et') && (
                      <small className="success-text">{t('user_management.help.valid_email')}</small>
                    )}
                  </div>
                </div>

                
                <div className="form-row">
                  <div className="form-group">
                    <label>{t('user_management.fields.role')} *</label>
                    <select
                      name="role"
                      value={newUser.role}
                      onChange={handleRoleChange}
                      required
                    >
                      <option value="employee">{t('roles.employee')}</option>
                      <option value="manager">{t('roles.manager')}</option>
                      <option value="hr-admin">{t('roles.hr-admin')}</option>
                      <option value="super-admin">{t('roles.super-admin')}</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label>{t('user_management.fields.department')} *</label>
                    <select
                      name="department"
                      value={isNewDepartment ? 'new' : newUser.department}
                      onChange={handleDepartmentChange}
                      required
                    >
                      <option value="">{t('user_management.placeholders.department')}</option>
                      {departments.map(dept => (
                        <option key={dept} value={dept}>{dept}</option>
                      ))}
                      <option value="new">+ {t('user_management.actions.add_department')}</option>
                    </select>
                    
                    {isNewDepartment && (
                      <input
                        type="text"
                        value={newDepartmentName}
                        onChange={handleNewDepartmentChange}
                        placeholder={t('user_management.placeholders.new_department')}
                        className="new-department-input"
                        required
                      />
                    )}
                  </div>
                </div>
              </div>

              <div className="form-section">
                <h4>{t('user_management.modal.additional_details')}</h4>
                <div className="form-row">
                  <div className="form-group">
                    <label>{t('user_management.fields.position')}</label>
                    <input
                      type="text"
                      name="position"
                      value={newUser.position}
                      onChange={handleInputChange}
                      placeholder={t('user_management.placeholders.position')}
                    />
                  </div>
                  <div className="form-group">
                    <label>{t('user_management.fields.phone')}</label>
                    <input
                      type="tel"
                      name="phone"
                      value={newUser.phone}
                      onChange={handleInputChange}
                      placeholder={t('user_management.placeholders.phone')}
                    />
                  </div>
                </div>

                {newUser.role === 'employee' && newUser.department && (
                  <div className="form-group">
                    <label>{t('user_management.fields.manager')}</label>
                    <select
                      name="managerId"
                      value={newUser.managerId}
                      onChange={handleInputChange}
                    >
                      <option value="">{t('user_management.placeholders.no_manager')}</option>
                      {availableManagers.map(manager => (
                        <option key={manager.id} value={manager.id}>
                          {manager.name} ({manager.email}) - {manager.position}
                        </option>
                      ))}
                    </select>
                    <small className="help-text">
                      {availableManagers.length === 0 && newUser.department 
                        ? t('user_management.help.no_managers', { department: newUser.department })
                        : t('user_management.help.select_manager')
                      }
                    </small>
                  </div>
                )}
              </div>

              <div className="form-section">
                <h4>{t('user_management.modal.security')}</h4>
                <div className="form-group">
                  <label>{t('user_management.fields.password')} *</label>
                  <div className="password-input-group">
                    <input
                      type="text"
                      name="password"
                      value={newUser.password}
                      onChange={handleInputChange}
                      required
                      placeholder={t('user_management.placeholders.password')}
                    />
                    <button 
                      type="button" 
                      className="generate-password-btn"
                      onClick={generatePassword}
                    >
                      {t('user_management.actions.generate_password')}
                    </button>
                  </div>
                  <small className="help-text">
                    {t('user_management.help.password_notice')}
                  </small>
                </div>
              </div>

              <div className="modal-actions">
                <button 
                  type="submit" 
                  className="save-btn primary"
                  disabled={actionLoading !== null}
                >
                  {actionLoading !== null ? t('user_management.actions.creating') : t('user_management.actions.create')}
                </button>
                <button 
                  type="button" 
                  className="cancel-btn"
                  onClick={() => {
                    setShowAddUser(false);
                    resetForm();
                  }}
                  disabled={actionLoading !== null}
                >
                  {t('common.cancel')}
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Users Table */}
      <div className="users-table-container">
        {filteredUsers.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">👥</div>
            <h3>{t('user_management.empty.title')}</h3>
            <p>
              {searchTerm || filterRole !== 'all' || filterDepartment !== 'all' 
                ? t('user_management.empty.filtered')
                : t('user_management.empty.default')
              }
            </p>
            <button 
              className="add-user-btn primary"
              onClick={() => setShowAddUser(true)}
            >
              {t('user_management.empty.add_first')}
            </button>
          </div>
        ) : (
          <>
            <table className="users-table">
              <thead>
                <tr>
                  <th>{t('user_management.table.user')}</th>
                  <th>{t('user_management.table.role')}</th>
                  <th>{t('user_management.table.department')}</th>
                  <th>{t('user_management.table.position')}</th>
                  <th>{t('user_management.table.join_date')}</th>
                  <th>{t('user_management.table.status')}</th>
                  <th>{t('user_management.table.actions')}</th>
                </tr>
              </thead>
              <tbody>
                {filteredUsers.map(user => (
                  <tr key={user.id} className={user.status === 'inactive' ? 'inactive-user' : ''}>
                    <td>
                      <div className="user-info">
                        <div className="user-avatar">
                          {user.avatar ? (
                            <img src={user.avatar} alt={user.name} />
                          ) : (
                            user.name?.charAt(0).toUpperCase()
                          )}
                        </div>
                        <div className="user-details">
                          <div className="user-name">{user.name}</div>
                          <div className="user-email">{user.email}</div>
                          {user.phone && (
                            <div className="user-phone">{user.phone}</div>
                          )}
                        </div>
                      </div>
                    </td>
                    <td>
                      <span className={`role-badge role-${user.role}`}>
                        {getRoleDisplayName(user.role)}
                      </span>
                    </td>
                    <td>{user.department}</td>
                    <td>{user.position || t('common.na')}</td>
                    <td>
                      {user.joinDate ? formatDate(user.joinDate) : t('common.na')}
                    </td>
                    <td>
                      <span className={`status-badge status-${user.status}`}>
                        {user.status === 'active' ? t('user_management.status.active') : t('user_management.status.inactive')}
                      </span>
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button 
                          className={`status-toggle-btn ${user.status === 'active' ? 'deactivate' : 'activate'}`}
                          onClick={() => handleStatusToggle(user.id, user.status || 'inactive')}
                          disabled={actionLoading === user.id}
                          title={user.status === 'active' ? t('user_management.actions.deactivate') : t('user_management.actions.activate')}
                        >
                          {actionLoading === user.id ? '...' : (user.status === 'active' ? t('user_management.actions.deactivate') : t('user_management.actions.activate'))}
                        </button>
                        <button 
                          className="delete-btn"
                          onClick={() => handleDeleteUser(user.id)}
                          disabled={actionLoading === user.id}
                          title={t('user_management.actions.delete')}
                        >
                          {actionLoading === user.id ? '...' : t('user_management.actions.delete')}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            
            <div className="table-footer">
              <div className="results-count">
                {t('user_management.table.showing', { shown: filteredUsers.length, total: users.length })}
                {(searchTerm || filterRole !== 'all' || filterDepartment !== 'all') && ` ${t('user_management.table.filtered')}`}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default UserManagement;
