import React, { useState, useEffect } from 'react';
import type{ User, UserFormData } from '../../types';
import { apiService } from '../../utils/api';
import './UserManagement.css';

const UserManagement: React.FC = () => {
  const [users, setUsers] = useState<User[]>([]);
  const [showAddUser, setShowAddUser] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(true);
  const [actionLoading, setActionLoading] = useState<number | null>(null);
  const [error, setError] = useState<string>('');
  const [success, setSuccess] = useState<string>('');
  const [searchTerm, setSearchTerm] = useState<string>('');
  const [filterRole, setFilterRole] = useState<string>('all');
  const [filterDepartment, setFilterDepartment] = useState<string>('all');
  const [managers, setManagers] = useState<User[]>([]);
  const [departments, setDepartments] = useState<string[]>([]);
  const [availableManagers, setAvailableManagers] = useState<User[]>([]);
  const [isNewDepartment, setIsNewDepartment] = useState<boolean>(false);
  const [newDepartmentName, setNewDepartmentName] = useState<string>('');
  const [emailError, setEmailError] = useState<string>('');

  const [autoGeneratedEmail, setAutoGeneratedEmail] = useState<string>('');
  
  const [newUser, setNewUser] = useState<UserFormData>({
    name: '',
    email: '',
    role: 'employee',
    department: '',
    position: '',
    phone: '',
    password: 'default123',
    managerId: ''
  });

  // Load users and initial data
  useEffect(() => {
    loadUsers();
    loadInitialData();
  }, []);

  const loadUsers = async () => {
    try {
      setLoading(true);
      setError('');
      const response = await apiService.getUsers();
      
      if (response.success) {
        setUsers(response.data || []);
        extractDepartments(response.data || []);
      } else {
        setError(response.message || 'Failed to load users');
      }
    } catch (error: any) {
      console.error('Error loading users:', error);
      setError(error.message || 'Failed to load users');
    } finally {
      setLoading(false);
    }
  };

  const loadInitialData = async () => {
    try {
      const response = await apiService.getUsers();
      if (response.success) {
        const allUsers = response.data || [];
        const managerUsers = allUsers.filter(user => 
          ['manager', 'hr-admin', 'super-admin'].includes(user.role)
        );
        setManagers(managerUsers);
        extractDepartments(allUsers);
      }
    } catch (error) {
      console.error('Error loading initial data:', error);
    }
  };

  const extractDepartments = (userList: User[]) => {
    const uniqueDepartments = [...new Set(
      userList
        .map(user => user.department)
        .filter(Boolean)
        .sort()
    )] as string[];
    setDepartments(uniqueDepartments);
  };

  // Generate email from name
  const generateEmailFromName = (name: string): string => {
    if (!name.trim()) return '';
    
    const nameParts = name.trim().split(' ').filter(part => part.length > 0);
    
    if (nameParts.length === 0) return '';
    
    // First name (all lowercase)
    const firstName = nameParts[0].toLowerCase();
    
    // Last name initial (capitalized)
    let lastNameInitial = '';
    if (nameParts.length > 1) {
      lastNameInitial = nameParts[nameParts.length - 1].charAt(0).toUpperCase();
    }
    
    // Generate base email
    let baseEmail = `${firstName}${lastNameInitial}`;
    
    // Remove special characters and non-English letters
    baseEmail = baseEmail.replace(/[^a-zA-Z]/g, '');
    
    // Add domain
    return `${baseEmail}@obu.edu.et`;
  };

  // Generate unique email by checking existing users
  const generateUniqueEmail = (baseEmail: string, existingUsers: User[]): string => {
    let finalEmail = baseEmail;
    let counter = 1;
    
    // Check if email already exists
    const emailExists = (email: string) => {
      return existingUsers.some(user => 
        user.email.toLowerCase() === email.toLowerCase() && user.status === 'active'
      );
    };
    
    // If base email exists, try with numbers
    while (emailExists(finalEmail) && counter < 100) {
      const [localPart] = baseEmail.split('@');
      finalEmail = `${localPart}${counter}@obu.edu.et`;
      counter++;
    }
    
    return finalEmail;
  };

  // Handle name change and auto-generate email
  const handleNameChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const name = e.target.value;
    
    setNewUser(prev => ({
      ...prev,
      name
    }));

    // Auto-generate email when name is entered
    if (name.trim().length > 0) {
      const generatedEmail = generateEmailFromName(name);
      setAutoGeneratedEmail(generatedEmail);
      
      // Only auto-fill email if it's empty or matches previous auto-generated pattern
      const currentEmail = newUser.email;
      const isAutoGenerated = currentEmail.includes('@obu.edu.et') || currentEmail === '';
      
      if (isAutoGenerated) {
        setNewUser(prev => ({
          ...prev,
          email: generatedEmail
        }));
      }
    } else {
      setAutoGeneratedEmail('');
    }

    // Clear messages when user starts typing
    if (success || error) {
      setSuccess('');
      setError('');
    }
  };

  // Handle manual email change
  const handleEmailChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const email = e.target.value;
    
    setNewUser(prev => ({
      ...prev,
      email
    }));

    setEmailError('');
    
    // Validate email format
    if (email && !email.includes('@obu.edu.et')) {
      setEmailError('Please use @obu.edu.et email domain');
    } else if (email && email.includes('@obu.edu.et')) {
      setEmailError('');
    }
  };

  // Regenerate email button handler
  const handleRegenerateEmail = () => {
    if (newUser.name.trim()) {
      const baseEmail = generateEmailFromName(newUser.name);
      const uniqueEmail = generateUniqueEmail(baseEmail, users);
      setNewUser(prev => ({
        ...prev,
        email: uniqueEmail
      }));
      setAutoGeneratedEmail(uniqueEmail);
      setEmailError('');
    }
  };

  // Load managers when department changes
  useEffect(() => {
    if (newUser.department && newUser.role === 'employee') {
      loadManagersForDepartment(newUser.department);
    } else {
      setAvailableManagers([]);
    }
  }, [newUser.department, newUser.role]);

  const loadManagersForDepartment = async (department: string) => {
    try {
      const departmentManagers = managers.filter(manager => 
        manager.department === department
      );
      setAvailableManagers(departmentManagers);
    } catch (error) {
      console.error('Error loading managers:', error);
      setAvailableManagers([]);
    }
  };

  const handleAddUser = async (e: React.FormEvent): Promise<void> => {
    e.preventDefault();
    
    try {
      setError('');
      setSuccess('');
      setEmailError('');

      // Validate all required fields
      if (!newUser.name || !newUser.email || !newUser.department) {
        setError('Please fill in all required fields');
        return;
      }

      // Validate email format
      if (!newUser.email.includes('@obu.edu.et')) {
        setEmailError('Please use @obu.edu.et email domain');
        return;
      }

      // Validate email doesn't exist in current active users
      const existingUser = users.find(user => 
        user.email.toLowerCase() === newUser.email.toLowerCase() && user.status === 'active'
      );

      if (existingUser) {
        setEmailError(`This email is already used by ${existingUser.name}`);
        return;
      }

      // Use new department name if "Add New" was selected
      const finalDepartment = isNewDepartment ? newDepartmentName : newUser.department;

      // Prepare user data
      const userData: any = {
        name: newUser.name.trim(),
        email: newUser.email.toLowerCase().trim(),
        role: newUser.role,
        department: finalDepartment.trim(),
        password: newUser.password
      };

      // Only add optional fields if they have values
      if (newUser.position?.trim()) userData.position = newUser.position.trim();
      if (newUser.phone?.trim()) userData.phone = newUser.phone.trim();

      // Only include managerId for employees and if manager is selected
      if (newUser.role === 'employee' && newUser.managerId) {
        userData.managerId = parseInt(newUser.managerId);
      }

      console.log('Creating user with data:', userData);

      const response = await apiService.createUser(userData);
      
      if (response.success) {
        setSuccess(`User "${newUser.name}" created successfully with email: ${newUser.email}`);
        await loadUsers();
        resetForm();
        setShowAddUser(false);
      } else {
        if (response.message?.includes('email already exists')) {
          // Auto-generate a new unique email and suggest it
          const newEmail = generateUniqueEmail(autoGeneratedEmail, users);
          setEmailError(`Email already exists. Suggested alternative: ${newEmail}`);
          setNewUser(prev => ({ ...prev, email: newEmail }));
        } else {
          setError(response.message || 'Failed to create user');
        }
      }
    } catch (error: any) {
      console.error('Error creating user:', error);
      
      if (error.message.includes('email already exists')) {
        const newEmail = generateUniqueEmail(autoGeneratedEmail, users);
        setEmailError(`Email already exists. Suggested alternative: ${newEmail}`);
        setNewUser(prev => ({ ...prev, email: newEmail }));
      } else {
        setError(error.message || 'Failed to create user');
      }
    }
  };

  const handleDeleteUser = async (userId: number): Promise<void> => {
    if (!window.confirm('Are you sure you want to delete this user? This action cannot be undone.')) {
      return;
    }

    try {
      setActionLoading(userId);
      setError('');
      setSuccess('');

      const response = await apiService.deleteUser(userId);
      
      if (response.success) {
        setSuccess('User deleted successfully!');
        await loadUsers();
      } else {
        setError(response.message || 'Failed to delete user');
      }
    } catch (error: any) {
      console.error('Error deleting user:', error);
      setError(error.message || 'Failed to delete user');
    } finally {
      setActionLoading(null);
    }
  };

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement | HTMLSelectElement>): void => {
    const { name, value } = e.target;
    setNewUser(prev => ({
      ...prev,
      [name]: value
    }));

    // Clear success/error when user starts typing
    if (success || error) {
      setSuccess('');
      setError('');
    }
  };

   const handleDepartmentChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const selectedValue = e.target.value;
    
    if (selectedValue === 'new') {
      setIsNewDepartment(true);
      setNewUser(prev => ({
        ...prev,
        department: ''
      }));
      setNewDepartmentName('');
    } else {
      setIsNewDepartment(false);
      setNewUser(prev => ({
        ...prev,
        department: selectedValue,
        managerId: ''
      }));
    }
  };

  const handleNewDepartmentChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    setNewDepartmentName(value);
    setNewUser(prev => ({
      ...prev,
      department: value
    }));
  };

  const handleRoleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
    const role = e.target.value;
    setNewUser(prev => ({
      ...prev,
      role,
      managerId: role !== 'employee' ? '' : prev.managerId
    }));
  };
  
  const handleStatusToggle = async (userId: number, currentStatus: string): Promise<void> => {
    const newStatus = currentStatus === 'active' ? 'inactive' : 'active';
    
    try {
      setActionLoading(userId);
      setError('');
      setSuccess('');

      // Update local state immediately for better UX
      setUsers(prevUsers => 
        prevUsers.map(user => 
          user.id === userId 
            ? { ...user, status: newStatus }
            : user
        )
      );

      setSuccess(`User ${newStatus === 'active' ? 'activated' : 'deactivated'} successfully!`);
      
      // TODO: Implement backend endpoint for status updates
      console.log(`Backend status update needed for user ${userId}: ${newStatus}`);
      
    } catch (error: any) {
      console.error('Error updating user status:', error);
      setError(error.message || 'Failed to update user status');
      
      // Revert local state on error
      setUsers(prevUsers => 
        prevUsers.map(user => 
          user.id === userId 
            ? { ...user, status: currentStatus }
            : user
        )
      );
    } finally {
      setActionLoading(null);
    }
  };

 const resetForm = (): void => {
    setNewUser({
      name: '',
      email: '',
      role: 'employee',
      department: '',
      position: '',
      phone: '',
      password: 'default123',
      managerId: ''
    });
    setIsNewDepartment(false);
    setNewDepartmentName('');
    setAvailableManagers([]);
    setEmailError('');
    setError('');
    setSuccess('');
    setAutoGeneratedEmail('');
  };

 const generatePassword = (): void => {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!@#$%^&*';
    let password = '';
    for (let i = 0; i < 12; i++) {
      password += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    setNewUser(prev => ({ ...prev, password }));
  };


  // Filter users based on search and filters
  const filteredUsers = users.filter(user => {
    const matchesSearch = user.name.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         user.email.toLowerCase().includes(searchTerm.toLowerCase());
    const matchesRole = filterRole === 'all' || user.role === filterRole;
    const matchesDepartment = filterDepartment === 'all' || user.department === filterDepartment;
    
    return matchesSearch && matchesRole && matchesDepartment;
  });

  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'short',
      day: 'numeric'
    });
  };

  const getRoleDisplayName = (role: string) => {
    const roleMap: { [key: string]: string } = {
      'employee': 'Employee',
      'manager': 'Manager',
      'hr-admin': 'HR Admin',
      'super-admin': 'Super Admin'
    };
    return roleMap[role] || role;
  };

  const clearMessages = (): void => {
    setError('');
    setSuccess('');
  };

  if (loading) {
    return (
      <div className="user-management">
        <div className="page-header">
          <h2>User Management</h2>
        </div>
        <div className="loading-state">
          <div className="loading-spinner"></div>
          <p>Loading users...</p>
        </div>
      </div>
    );
  }

  return (
    <div className="user-management">
      <div className="page-header">
        <div className="header-content">
          <div className="header-title">
            <h2>User Management</h2>
            <span className="user-count-badge">{users.length} users</span>
          </div>
          <button 
            className="add-user-btn primary"
            onClick={() => setShowAddUser(true)}
          >
            <span className="btn-icon">+</span>
            Add User
          </button>
        </div>
      </div>

      {/* Filters and Search */}
      <div className="filters-section">
        <div className="search-box">
          <input
            type="text"
            placeholder="Search users by name or email..."
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="search-input"
          />
          <span className="search-icon">🔍</span>
        </div>
        
        <div className="filter-controls">
          <select 
            value={filterRole} 
            onChange={(e) => setFilterRole(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Roles</option>
            <option value="employee">Employee</option>
            <option value="manager">Manager</option>
            <option value="hr-admin">HR Admin</option>
            <option value="super-admin">Super Admin</option>
          </select>

          <select 
            value={filterDepartment} 
            onChange={(e) => setFilterDepartment(e.target.value)}
            className="filter-select"
          >
            <option value="all">All Departments</option>
            {departments.map(dept => (
              <option key={dept} value={dept}>{dept}</option>
            ))}
          </select>

          <button 
            className="refresh-btn"
            onClick={loadUsers}
            title="Refresh users"
          >
            🔄 Refresh
          </button>
        </div>
      </div>

      {/* Messages */}
      {error && (
        <div className="message-banner error">
          <div className="message-content">
            <span className="message-icon">❌</span>
            {error}
          </div>
          <button onClick={clearMessages} className="message-close">×</button>
        </div>
      )}

      {success && (
        <div className="message-banner success">
          <div className="message-content">
            <span className="message-icon">✅</span>
            {success}
          </div>
          <button onClick={clearMessages} className="message-close">×</button>
        </div>
      )}

      {/* Add User Modal */}
       {showAddUser && (
        <div className="modal-overlay">
          <div className="modal-content">
            <div className="modal-header">
              <h3>Add New User</h3>
              <button 
                className="close-btn"
                onClick={() => {
                  setShowAddUser(false);
                  resetForm();
                }}
              >
                ×
              </button>
            </div>
            
            <form onSubmit={handleAddUser} className="user-form">
              <div className="form-section">
                <h4>Basic Information</h4>
                <div className="form-row">
                  <div className="form-group">
                    <label>Full Name *</label>
                    <input
                      type="text"
                      name="name"
                      value={newUser.name}
                      onChange={handleNameChange}
                      required
                      placeholder="Enter full name (e.g., Obsa Mustefa)"
                    />
                  <small className="help-text">
                      Enter first name and last name for automatic email generation
                    </small>
                  </div>
                  <div className="form-group">
                    <label>Email *</label>
                    <div className="email-input-group">
                      <input
                        type="email"
                        name="email"
                        value={newUser.email}
                        onChange={handleEmailChange}
                        required
                        placeholder="Email will be auto-generated"
                        className={emailError ? 'error' : (newUser.email ? 'success' : '')}
                      />
                      <button 
                        type="button" 
                        className="generate-email-btn"
                        onClick={handleRegenerateEmail}
                        disabled={!newUser.name.trim()}
                        title="Generate new email"
                      >
                        🔄
                      </button>
                    </div>
                    {autoGeneratedEmail && (
                      <small className="help-text">
                        Auto-generated: {autoGeneratedEmail}
                      </small>
                    )}
                    {emailError && (
                      <small className="error-text">{emailError}</small>
                    )}
                    {!emailError && newUser.email && newUser.email.includes('@obu.edu.et') && (
                      <small className="success-text">✓ Valid OBU email</small>
                    )}
                  </div>
                </div>

                
                <div className="form-row">
                  <div className="form-group">
                    <label>Role *</label>
                    <select
                      name="role"
                      value={newUser.role}
                      onChange={handleRoleChange}
                      required
                    >
                      <option value="employee">Employee</option>
                      <option value="manager">Manager</option>
                      <option value="hr-admin">HR Admin</option>
                      <option value="super-admin">Super Admin</option>
                    </select>
                  </div>
                  <div className="form-group">
                    <label>Department *</label>
                    <select
                      name="department"
                      value={isNewDepartment ? 'new' : newUser.department}
                      onChange={handleDepartmentChange}
                      required
                    >
                      <option value="">Select Department</option>
                      {departments.map(dept => (
                        <option key={dept} value={dept}>{dept}</option>
                      ))}
                      <option value="new">+ Add New Department</option>
                    </select>
                    
                    {isNewDepartment && (
                      <input
                        type="text"
                        value={newDepartmentName}
                        onChange={handleNewDepartmentChange}
                        placeholder="Enter new department name"
                        className="new-department-input"
                        required
                      />
                    )}
                  </div>
                </div>
              </div>

              <div className="form-section">
                <h4>Additional Details</h4>
                <div className="form-row">
                  <div className="form-group">
                    <label>Position</label>
                    <input
                      type="text"
                      name="position"
                      value={newUser.position}
                      onChange={handleInputChange}
                      placeholder="e.g., Software Engineer"
                    />
                  </div>
                  <div className="form-group">
                    <label>Phone</label>
                    <input
                      type="tel"
                      name="phone"
                      value={newUser.phone}
                      onChange={handleInputChange}
                      placeholder="e.g., +1234567890"
                    />
                  </div>
                </div>

                {newUser.role === 'employee' && newUser.department && (
                  <div className="form-group">
                    <label>Assign Manager</label>
                    <select
                      name="managerId"
                      value={newUser.managerId}
                      onChange={handleInputChange}
                    >
                      <option value="">No Manager (Self-managed)</option>
                      {availableManagers.map(manager => (
                        <option key={manager.id} value={manager.id}>
                          {manager.name} ({manager.email}) - {manager.position}
                        </option>
                      ))}
                    </select>
                    <small className="help-text">
                      {availableManagers.length === 0 && newUser.department 
                        ? `No managers found in ${newUser.department} department`
                        : 'Select a manager from the same department'
                      }
                    </small>
                  </div>
                )}
              </div>

              <div className="form-section">
                <h4>Security</h4>
                <div className="form-group">
                  <label>Initial Password *</label>
                  <div className="password-input-group">
                    <input
                      type="text"
                      name="password"
                      value={newUser.password}
                      onChange={handleInputChange}
                      required
                      placeholder="Set initial password"
                    />
                    <button 
                      type="button" 
                      className="generate-password-btn"
                      onClick={generatePassword}
                    >
                      Generate
                    </button>
                  </div>
                  <small className="help-text">
                    User will be asked to change this password on first login
                  </small>
                </div>
              </div>

              <div className="modal-actions">
                <button 
                  type="submit" 
                  className="save-btn primary"
                  disabled={actionLoading !== null}
                >
                  {actionLoading !== null ? 'Creating...' : 'Create User'}
                </button>
                <button 
                  type="button" 
                  className="cancel-btn"
                  onClick={() => {
                    setShowAddUser(false);
                    resetForm();
                  }}
                  disabled={actionLoading !== null}
                >
                  Cancel
                </button>
              </div>
            </form>
          </div>
        </div>
      )}

      {/* Users Table */}
      <div className="users-table-container">
        {filteredUsers.length === 0 ? (
          <div className="empty-state">
            <div className="empty-icon">👥</div>
            <h3>No Users Found</h3>
            <p>
              {searchTerm || filterRole !== 'all' || filterDepartment !== 'all' 
                ? 'Try adjusting your search or filters'
                : 'Get started by adding your first user to the system.'
              }
            </p>
            <button 
              className="add-user-btn primary"
              onClick={() => setShowAddUser(true)}
            >
              Add First User
            </button>
          </div>
        ) : (
          <>
            <table className="users-table">
              <thead>
                <tr>
                  <th>User</th>
                  <th>Role</th>
                  <th>Department</th>
                  <th>Position</th>
                  <th>Join Date</th>
                  <th>Status</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                {filteredUsers.map(user => (
                  <tr key={user.id} className={user.status === 'inactive' ? 'inactive-user' : ''}>
                    <td>
                      <div className="user-info">
                        <div className="user-avatar">
                          {user.avatar ? (
                            <img src={user.avatar} alt={user.name} />
                          ) : (
                            user.name?.charAt(0).toUpperCase()
                          )}
                        </div>
                        <div className="user-details">
                          <div className="user-name">{user.name}</div>
                          <div className="user-email">{user.email}</div>
                          {user.phone && (
                            <div className="user-phone">{user.phone}</div>
                          )}
                        </div>
                      </div>
                    </td>
                    <td>
                      <span className={`role-badge role-${user.role}`}>
                        {getRoleDisplayName(user.role)}
                      </span>
                    </td>
                    <td>{user.department}</td>
                    <td>{user.position || '-'}</td>
                    <td>
                      {user.joinDate ? formatDate(user.joinDate) : 'N/A'}
                    </td>
                    <td>
                      <span className={`status-badge status-${user.status}`}>
                        {user.status}
                      </span>
                    </td>
                    <td>
                      <div className="action-buttons">
                        <button 
                          className={`status-toggle-btn ${user.status === 'active' ? 'deactivate' : 'activate'}`}
                          onClick={() => handleStatusToggle(user.id, user.status)}
                          disabled={actionLoading === user.id}
                          title={user.status === 'active' ? 'Deactivate user' : 'Activate user'}
                        >
                          {actionLoading === user.id ? '...' : (user.status === 'active' ? 'Deactivate' : 'Activate')}
                        </button>
                        <button 
                          className="delete-btn"
                          onClick={() => handleDeleteUser(user.id)}
                          disabled={actionLoading === user.id}
                          title="Delete user"
                        >
                          {actionLoading === user.id ? '...' : 'Delete'}
                        </button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
            
            <div className="table-footer">
              <div className="results-count">
                Showing {filteredUsers.length} of {users.length} user{users.length !== 1 ? 's' : ''}
                {(searchTerm || filterRole !== 'all' || filterDepartment !== 'all') && ' (filtered)'}
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
};

export default UserManagement;